name: medic
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  velocity_x: ^4.1.1
  bloc: ^8.1.2
  table_calendar: ^3.0.0
  firebase_core: ^2.19.0
  cloud_firestore: ^4.11.0
  firebase_storage: ^11.3.1
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
